apiVersion: v1
kind: Deployment
metadata:
  name: go-server
  labels:
    - app: "goserver"
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "eduardogomesf/hello-go:latest"
          envFrom:
            - configMapRef:
                name: goserver-env
            # The example below show how to get individual values
            # - name: NAME
            #   valueFrom:
            #     configMapKeyRef:
            #       name: goserver-env
            #       key: NAME